# Generated by Django 5.2.1 on 2025-06-27 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('EnAttente', 'En Attente'), ('EnCours', 'En Cours'), ('Satisfaite', 'Satisfaite'), ('NonSatisfaite', 'Non Satisfaite')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('autre', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeCompetence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experience', models.CharField(max_length=255)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compat.competence')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='compat.demande')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilCandidat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('Prospection', 'Prospection'), ('Invite', 'Invite'), ('Inscrit', 'Inscrit')], max_length=20)),
                ('prospecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plateforme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Scrapping', 'Scrapping'), ('API', 'Api')], max_length=20)),
                ('candidats', models.ManyToManyField(related_name='plateformes', to='compat.profilcandidat')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('envoi_automatique', models.BooleanField(default=False)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='compat.demande')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='compat.profilcandidat')),
            ],
        ),
        migrations.CreateModel(
            name='Correspondance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_compatibilite', models.FloatField()),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondances', to='compat.demande')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondances', to='compat.profilcandidat')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilCompetence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experience', models.CharField(max_length=255)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compat.competence')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='compat.profilcandidat')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilLangue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compat.langue')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langues', to='compat.profilcandidat')),
            ],
        ),
    ]
